locals {
  node_name = "cle-pve"

  qemu_guests = {
    homelab_pve = {
      vm_id               = 101
      name                = "homelab-pve"
      description         = "generated by NixOS"
      cores               = 8
      memory              = 8192
      boot_disk_datastore = "fast-vm"
      boot_disk_size      = 200
      cloudinit_datastore = "local-zfs"
      mac_address         = "BC:24:11:8B:69:FC"
      startup_order       = 80
      startup_up_delay    = 30
      startup_down_delay  = 0
      vga_type            = null
    }

    selfhost_pve = {
      vm_id               = 121
      name                = "selfhost-pve"
      description         = "generated by NixOS"
      cores               = 8
      memory              = 8192
      boot_disk_datastore = "fast-vm"
      boot_disk_size      = 320
      cloudinit_datastore = "fast-vm"
      mac_address         = "BC:24:11:50:01:21"
      startup_order       = 70
      startup_up_delay    = 45
      startup_down_delay  = 0
      vga_type            = "serial0"
    }
  }

  windows11_vm = {
    vm_id               = 100
    name                = "windows11"
    description         = "Windows 11 VM imported from /fast/domains/Windows11/vdisk1.img"
    cores               = 4
    memory              = 8192
    boot_disk_datastore = "fast-vm"
    boot_disk_size      = 40
    import_file_id      = "local:import/Windows11-vdisk1.qcow2"
    virtio_iso_file_id  = "local:iso/virtio-win-0.1.271-1.iso"
    mac_address         = "BC:24:11:50:01:00"
  }

  lxc_guests = {
    pulse = {
      vm_id              = 102
      hostname           = "pulse"
      description        = "Pulse monitoring LXC from community-scripts"
      tags               = ["community-script", "monitoring", "proxmox"]
      cores              = 1
      memory             = 1024
      swap               = 512
      rootfs_datastore   = "local-zfs"
      rootfs_size        = 4
      mac_address        = "BC:24:11:4D:C6:9E"
      startup_order      = 10
      startup_up_delay   = 10
      startup_down_delay = 0
      unprivileged       = true
      features           = { nesting = true, keyctl = true, fuse = false }
      mount_points       = []
      devices = [
        { path = "/dev/net/tun", gid = null, mode = "0666" },
      ]
    }

    plex_pve = {
      vm_id              = 110
      hostname           = "plex-pve"
      description        = "Plex with Intel iGPU passthrough"
      tags               = []
      cores              = 4
      memory             = 4096
      swap               = 1024
      rootfs_datastore   = "fast-vm"
      rootfs_size        = 24
      mac_address        = "BC:24:11:50:01:10"
      startup_order      = 30
      startup_up_delay   = 15
      startup_down_delay = 0
      unprivileged       = true
      features           = { nesting = true, keyctl = true, fuse = true }
      mount_points = [
        { volume = "/tank/media", path = "/data", read_only = true },
      ]
      devices = [
        { path = "/dev/dri/renderD128", gid = 1000, mode = "0660" },
        { path = "/dev/dri/card0", gid = 1000, mode = "0660" },
        { path = "/dev/net/tun", gid = null, mode = "0666" },
      ]
    }

    jellyfin_pve = {
      vm_id              = 111
      hostname           = "jellyfin-pve"
      description        = "Jellyfin with Intel iGPU passthrough"
      tags               = []
      cores              = 2
      memory             = 2048
      swap               = 512
      rootfs_datastore   = "fast-vm"
      rootfs_size        = 24
      mac_address        = "BC:24:11:50:01:11"
      startup_order      = 40
      startup_up_delay   = 15
      startup_down_delay = 0
      unprivileged       = true
      features           = { nesting = true, keyctl = true, fuse = true }
      mount_points = [
        { volume = "/tank/media", path = "/data", read_only = true },
      ]
      devices = [
        { path = "/dev/dri/renderD128", gid = 1000, mode = "0660" },
        { path = "/dev/dri/card0", gid = 1000, mode = "0660" },
        { path = "/dev/net/tun", gid = null, mode = "0666" },
      ]
    }

    nas_pve = {
      vm_id              = 112
      hostname           = "nas-pve"
      description        = "NFS/Samba shared data export"
      tags               = []
      cores              = 1
      memory             = 512
      swap               = 256
      rootfs_datastore   = "fast-vm"
      rootfs_size        = 16
      mac_address        = "BC:24:11:50:01:12"
      startup_order      = 20
      startup_up_delay   = 15
      startup_down_delay = 0
      unprivileged       = false
      features           = { nesting = true, keyctl = false, fuse = false }
      mount_points = [
        { volume = "/tank/media", path = "/shares/media", read_only = false },
        { volume = "/fast/zk", path = "/shares/zk", read_only = false },
      ]
      devices = []
    }

    frigate_pve = {
      vm_id              = 113
      hostname           = "frigate-pve"
      description        = "Frigate with Intel iGPU passthrough"
      tags               = []
      cores              = 4
      memory             = 4096
      swap               = 1024
      rootfs_datastore   = "fast-vm"
      rootfs_size        = 24
      mac_address        = "BC:24:11:50:01:13"
      startup_order      = 50
      startup_up_delay   = 30
      startup_down_delay = 0
      unprivileged       = true
      features           = { nesting = true, keyctl = true, fuse = true }
      mount_points = [
        { volume = "/tank/frigate/storage", path = "/media/frigate", read_only = false },
      ]
      devices = [
        { path = "/dev/dri/renderD128", gid = 992, mode = "0660" },
        { path = "/dev/dri/card0", gid = 44, mode = "0660" },
      ]
    }

    immich_pve = {
      vm_id              = 114
      hostname           = "immich-pve"
      description        = "Immich with iGPU/OpenVINO"
      tags               = []
      cores              = 6
      memory             = 4096
      swap               = 1024
      rootfs_datastore   = "fast-vm"
      rootfs_size        = 32
      mac_address        = "BC:24:11:50:01:14"
      startup_order      = 60
      startup_up_delay   = 45
      startup_down_delay = 0
      unprivileged       = true
      features           = { nesting = true, keyctl = true, fuse = true }
      mount_points = [
        { volume = "/fast/immich-app", path = "/mnt/user/immich-app", read_only = false },
      ]
      devices = [
        { path = "/dev/dri/renderD128", gid = 992, mode = "0660" },
        { path = "/dev/dri/card0", gid = 44, mode = "0660" },
        { path = "/dev/net/tun", gid = null, mode = "0666" },
      ]
    }

    backup_pve = {
      vm_id              = 115
      hostname           = "backup-pve"
      description        = "Kopia backup server"
      tags               = []
      cores              = 2
      memory             = 1536
      swap               = 512
      rootfs_datastore   = "fast-vm"
      rootfs_size        = 8
      mac_address        = "BC:24:11:BF:01:71"
      startup_order      = 65
      startup_up_delay   = 20
      startup_down_delay = 0
      unprivileged       = false
      features           = { nesting = true, keyctl = false, fuse = false }
      mount_points = [
        { volume = "/fast/immich-app", path = "/source/immich-app", read_only = true },
        { volume = "/tank/fast-backups", path = "/backups", read_only = false },
      ]
      devices = []
    }
  }
}
